# Generated by Django 4.1.3 on 2022-11-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0003_remove_super_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='super',
            name='supertype',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
        ),
    ]
