# Generated by Django 4.1.3 on 2022-11-15 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('super_types', '0001_initial'),
        ('supers', '0004_super_supertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='super',
            name='supertype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='super_types.supertype'),
            preserve_default=False,
        ),
    ]
